CUDA_VISIBLE_DEVICES=2 python ../src/combiner_train.py \
        --dataset "FashionIQ" \
        --projection-dim 2560 \
        --hidden-dim 5120   \
        --num-epochs 300 \
        --clip-model-name RN50 \
        --combiner-lr 2e-5 --batch-size 128 \
        --clip-bs 32 --transform targetpad --target-ratio 1.25 \
        --save-training \
        --save-best --validation-frequency 1 \
        --output-dir "/data/zhuyingying/multimodal_retrieval/logs/"