#include <iostream>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <math.h>
#include "jerasure.h"
#include "cauchy.h"
#include "PIM_InputParameter.h"
#include "SubArray.h"
#include "Bank.h"
#include "Controller.h"
#include "Trace_collect.h"
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <vector>
